### ISSUE TITLE
Strange behavior of the exit dialog

### ISSUE THREAD

**Issue by georgy7** [georgy7/catframes#30]
Current behavior:
FFmpeg and catframes.py execution continues after closing the window with an unfinished task.

Expected behavior:
After clicking the Leave button, all processes are terminated, all unfinished video files are deleted.

Commit: d7ceb6f4b2648b1b5d2ca92ca2458a37238d5fcc
Platform: Win10 Pro.

---

Also, if catframes failed to start, clicking on the Leave button does not close the window. Instead, the Cancel button changes to the Delete button. Clicking on the cross again closes the window.

Console output:

```
C:\Users\Admin>C:\Dist\catframes\src\catframes\catmanager.py

FFmpeg not found.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Dist\catframes\src\catframes\catmanager.py", line 1665, in canvas_updater
    self.change_canvas_resolution(resolution)
  File "C:\Dist\catframes\src\catframes\catmanager.py", line 1643, in change_canvas_resolution
    canvas_height_change = self.image_canvas.update_resolution(resolution)
  File "C:\Dist\catframes\src\catframes\catmanager.py", line 1062, in update_resolution
    ratio = resolution[0]/resolution[1]  # вычисляет соотношение сторон разрешения рендера
TypeError: 'NoneType' object is not subscriptable

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Dist\catframes\src\catframes\catmanager.py", line 1860, in exit
    task.cancel()
  File "C:\Dist\catframes\src\catframes\catmanager.py", line 453, in cancel
    self._process_thread.kill()        # убивает процесс
  File "C:\Dist\catframes\src\catframes\catmanager.py", line 406, in kill
    os.kill(self.process.pid, signal.SIGABRT)
PermissionError: [WinError 5] Отказано в доступе

C:\Users\Admin>
```

This task is related to #28

**Comment by NeiroSlav** [comment]
Done
